version: '3.4'

services:

  # Redis
  redis:
    image: redis:${REDIS_VERSION}
    container_name: live-redis
    restart: unless-stopped
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
    ports:
      - "6379:6379"