# This is a basic workflow to help you get started with Actions

name: Docker Compose Workflow

on:
  workflow_dispatch

env:
  TEST_VERSION=0.0.1

jobs:
  build-step:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Print replaced version?!
      - name: Do something
        run: | 
          sed -i 's/<replace-me>/${{env.TEST_VERSION}}/g' ./deployment/docker-compose/.env.github
          cat ./deployment/docker-compose/.env.github

      - uses: isbang/compose-action@v1.3.2
        with:
          compose-file: "./deployment/docker-compose/docker-compose.test-services.yml"
          compose-flags: --env-file=./deployment/docker-compose/.env.github
        env:
          CUSTOM_VARIABLE: "test"
          services: |
            redis