# This is a basic workflow to help you get started with Actions

name: Docker Compose Workflow

on:
  workflow_dispatch

jobs:
  build-step:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Find and Replace 
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          include: "./deployment/docker-compose/.env.github"
          find: "<replace-me>"
          replace:  '6.2.4'
          regex: false

      - uses: isbang/compose-action@v1.3.2
        with:
          compose-file: "./deployment/docker-compose/docker-compose.test-services.yml"
          compose-flags: --env-file=./deployment/docker-compose/.env.github
        env:
          CUSTOM_VARIABLE: "test"
          services: |
            redis