name: Integration Tests

on:
  workflow_dispatch

jobs:
  setup-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: container-setup
        name: Setup SQL Server in Docker
        run: |
          docker run --name sql-container -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=yourStrong(!)Password" -p 1433:1433 -d mcr.microsoft.com/mssql/server:2022-latest

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - id: build-code
        name: Build .NET project
        run: |
          dotnet build IntegrationTestPlayground/IntegrationTestPlayground.sln

      - id: run-code
        name: Run code
        run: |
          dotnet run --project IntegrationTestPlayground/MyProgram/MyProgram.csproj "Data Source=sql-container;Initial Catalog=master;User Id=sa;Password=yourStrong(!)Password;"
