name: Workflow Dispatch Test

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number year.major.patch (2022.1.2)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.foo.outputs.test }}
    steps:
      - uses: actions/checkout@v3

      - id: foo
        uses: ./.github/actions/get-build-number
        with:
          version-number: ${{ github.run_number }}${{ github.run_attempt }}

      - id: output-test
        name: Run a one-line script
        run: |
          echo Build number is ${{ steps.build-date.outputs.date }}.${{ github.run_attempt }}
