name: Workflow Dispatch Test

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number year.major.patch (2022.1.2)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.foo.outputs.test }}
    steps:
      - uses: actions/checkout@v3

      - name: Get current date
        id: build-date
        run: echo "build-date-output=${{env.BUILD_VERSION}}.$GITHUB_RUN_ATTEMPT" >> $GITHUB_OUTPUT
        shell: bash

      - name: Set output
        run: echo "MYVALUE=can you read this?" >> $GITHUB_OUTPUT

      - id: output-test
        name: Run a one-line script
        run: |
          echo Build number is ${{ steps.build-date.outputs.date }}.${{ github.run_attempt }}
