name: Workflow Dispatch Test

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number year.major.patch (2022.1.2)'
        required: true

jobs:
  generate-build-version:
    runs-on: ubuntu-latest
    outputs:
      build-version: ${{ steps.set-build-number.outputs.build-date-output }}

    steps:

      - id: set-build-number
        name: Set output
        run: echo "build-date-output=$(date +'%Y.%m.%d').${{ github.run_number }}${{ github.run_attempt }}" >> $GITHUB_OUTPUT

      - id: print-build-number
        name: Print the build number from the previous step
        run: |
          echo Build number is ${{ steps.set-build-number.outputs.build-date-output }}

  consume-build-version:
    runs-on: ubuntu-latest
    needs: generate-build-version
    steps:
      - env:
          OUTPUT1: ${{needs.generate-build-version.outputs.build-version}}
        run: |
          echo "Build number $OUTPUT1"
