name: Workflow Dispatch Test

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number year.major.patch (2022.1.2)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.get-build-number.outputs.HELLO }}

    steps:
      - uses: actions/checkout@v3

      - id: get-build-number
        uses: ./.github/actions/get-build-number
        with:
          version-number: ${{ github.run_number }}${{ github.run_attempt }}

      - id: output-my-value
        name: Set output
        run: echo "MYVALUE=can you read this?" >> $GITHUB_OUTPUT

      - id: output-test
        name: Run a one-line script
        run: |
          echo Build number is ${{ steps.output-my-value.outputs.MYVALUE }}
          echo Build number is ${{ steps.get-build-number.outputs.HELLO }}
          echo Build number is ${{ steps.get-build-number.outputs.HELLO }}

  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test=world" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - env:
          OUTPUT1: ${{needs.build.outputs.output1}}
        run: echo "This should be something $OUTPUT1"