# This is a basic workflow to help you get started with Actions

name: Workflow Dispatch Test

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number year.major.patch (2022.1.2)'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.foo.outputs.test }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Get current date
        id: build-date
        run: echo "::set-output name=date::$(date +'%Y.%m.%d')"

      - id: foo
        uses: ./.github/actions/get-build-number
        with:
          version-number: ${{ github.run_number }}${{ github.run_attempt }}

      # Runs a single command using the runners shell
      - id: output-test
        name: Run a one-line script
        run: |
          echo Build number is ${{ steps.build-date.outputs.date }}.${{ github.run_attempt }}
          echo Build number is ${{ steps.foo.outputs.build-number }}
          echo Im in the branch ${GITHUB_REF#refs/heads/}
          echo ::set-output name=test::${{ steps.foo.outputs.build-number }}
