name: Write PDF

on:
  push

jobs:
  generate-pdf:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Write MD file
        uses: DamianReeves/write-file-action@master
        with:
          path: docs/test.md
          contents: |
            Hello World!
            Here's some information about the run ${{ github.run_number }}${{ github.run_attempt }}
          write-mode: append

      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: docs
          output_dir: pdfs
          # images_dir: docs/images
          # for example <img src="./images/file-name.png">
          # image_import: ./images
          # Default is true, can set to false to only get PDF files
          # build_html: false

      - uses: actions/upload-artifact@v1
        name: Upload PDF file
        with:
          name: platform-architecture-docs
          path: pdfs

              
              
            