name: Write PDF

on:
  push

jobs:
  generate-pdf:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Write MD file
        uses: DamianReeves/write-file-action@master
        with:
          path: doc/test.md
          contents: |
            Hello World!
            Here's some information about the run ${{ github.run_number }}${{ github.run_attempt }}
        write-mode: append

      - uses: mkrakowitzer/actions-makepdfs@master
        name: Convert to PDF
        with:
          markdown_dir: doc
          output_dir: tmp

      - uses: actions/upload-artifact@v1
        name: Upload PDF file
        with:
          name: platform-architecture-docs
          path: tmp

              
              
            