name: Write PDF

on:
  push

jobs:
  generate-pdf:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - id: write-some-markdown
        name: Write some markdown
        run: |
          touch ./doc/test.md
          echo "Hello this is a message from GitHub Actions. Here's some information about the run ${{ github.run_number }}${{ github.run_attempt }}" >> ./doc/test.md

      - uses: mkrakowitzer/actions-makepdfs@master
        name: Convert to PDF
        with:
          markdown_dir: doc
          output_dir: tmp

      - uses: actions/upload-artifact@v1
        name: Upload PDF file
        with:
          name: platform-architecture-docs
          path: tmp

              
              
            